export const data = [
  {
    game_name: "Adventure Quest",
    game_id: "G001",
    client_id: "C001",
    create_date: "2024-01-10",
    active_status: true,
    genre: "Adventure",
    image_link: "https://example.com/images/adventure_quest.jpg",
    bundle_price: 19.99,
  },
  {
    game_name: "Space Invaders",
    game_id: "G002",
    client_id: "C002",
    create_date: "2024-02-15",
    active_status: true,
    genre: "Shooter",
    image_link: "https://example.com/images/space_invaders.jpg",
    bundle_price: 9.99,
  },
  {
    game_name: "Puzzle Master",
    game_id: "G003",
    client_id: "C003",
    create_date: "2024-03-20",
    active_status: false,
    genre: "Puzzle",
    image_link: "https://example.com/images/puzzle_master.jpg",
    bundle_price: 14.99,
  },
  {
    game_name: "Racing Legends",
    game_id: "G004",
    client_id: "C004",
    create_date: "2024-04-25",
    active_status: true,
    genre: "Racing",
    image_link: "https://example.com/images/racing_legends.jpg",
    bundle_price: 29.99,
  },
  {
    game_name: "Mystery Mansion",
    game_id: "G005",
    client_id: "C005",
    create_date: "2024-05-30",
    active_status: true,
    genre: "Mystery",
    image_link: "https://example.com/images/mystery_mansion.jpg",
    bundle_price: 24.99,
  },
  {
    game_name: "Zombie Survival",
    game_id: "G006",
    client_id: "C006",
    create_date: "2024-06-15",
    active_status: true,
    genre: "Survival",
    image_link: "https://example.com/images/zombie_survival.jpg",
    bundle_price: 39.99,
  },
  {
    game_name: "Fantasy Battle",
    game_id: "G007",
    client_id: "C007",
    create_date: "2024-07-20",
    active_status: false,
    genre: "Fantasy",
    image_link: "https://example.com/images/fantasy_battle.jpg",
    bundle_price: 34.99,
  },
  {
    game_name: "Historical Wars",
    game_id: "G008",
    client_id: "C008",
    create_date: "2024-08-05",
    active_status: true,
    genre: "Strategy",
    image_link: "https://example.com/images/historical_wars.jpg",
    bundle_price: 44.99,
  },
  {
    game_name: "Virtual Farm",
    game_id: "G009",
    client_id: "C009",
    create_date: "2024-09-10",
    active_status: true,
    genre: "Simulation",
    image_link: "https://example.com/images/virtual_farm.jpg",
    bundle_price: 19.99,
  },
  {
    game_name: "Dungeon Escape",
    game_id: "G010",
    client_id: "C010",
    create_date: "2024-10-25",
    active_status: false,
    genre: "Action",
    image_link: "https://example.com/images/dungeon_escape.jpg",
    bundle_price: 14.99,
  },
  {
    game_name: "Stealth Agent",
    game_id: "G011",
    client_id: "C011",
    create_date: "2024-11-01",
    active_status: true,
    genre: "Stealth",
    image_link: "https://example.com/images/stealth_agent.jpg",
    bundle_price: 24.99,
  },
  {
    game_name: "Battle Royale",
    game_id: "G012",
    client_id: "C012",
    create_date: "2024-12-01",
    active_status: true,
    genre: "Battle Royale",
    image_link: "https://example.com/images/battle_royale.jpg",
    bundle_price: 29.99,
  },
  {
    game_name: "Cyber Quest",
    game_id: "G013",
    client_id: "C013",
    create_date: "2024-01-12",
    active_status: true,
    genre: "Sci-Fi",
    image_link: "https://example.com/images/cyber_quest.jpg",
    bundle_price: 34.99,
  },
  {
    game_name: "Pirate Adventures",
    game_id: "G014",
    client_id: "C014",
    create_date: "2024-02-18",
    active_status: true,
    genre: "Adventure",
    image_link: "https://example.com/images/pirate_adventures.jpg",
    bundle_price: 19.99,
  },
  {
    game_name: "City Builder",
    game_id: "G015",
    client_id: "C015",
    create_date: "2024-03-25",
    active_status: false,
    genre: "Simulation",
    image_link: "https://example.com/images/city_builder.jpg",
    bundle_price: 24.99,
  },
  {
    game_name: "Epic Battles",
    game_id: "G016",
    client_id: "C016",
    create_date: "2024-04-30",
    active_status: true,
    genre: "Strategy",
    image_link: "https://example.com/images/epic_battles.jpg",
    bundle_price: 39.99,
  },
  {
    game_name: "Ghost Hunter",
    game_id: "G017",
    client_id: "C017",
    create_date: "2024-05-12",
    active_status: true,
    genre: "Horror",
    image_link: "https://example.com/images/ghost_hunter.jpg",
    bundle_price: 29.99,
  },
  {
    game_name: "Survival Island",
    game_id: "G018",
    client_id: "C018",
    create_date: "2024-06-22",
    active_status: true,
    genre: "Survival",
    image_link: "https://example.com/images/survival_island.jpg",
    bundle_price: 34.99,
  },
  {
    game_name: "Robot Wars",
    game_id: "G019",
    client_id: "C019",
    create_date: "2024-07-10",
    active_status: false,
    genre: "Sci-Fi",
    image_link: "https://example.com/images/robot_wars.jpg",
    bundle_price: 39.99,
  },
  {
    game_name: "Castle Defense",
    game_id: "G020",
    client_id: "C020",
    create_date: "2024-08-15",
    active_status: true,
    genre: "Strategy",
    image_link: "https://example.com/images/castle_defense.jpg",
    bundle_price: 29.99,
  },
  {
    game_name: "Deep Sea Explorer",
    game_id: "G021",
    client_id: "C021",
    create_date: "2024-09-25",
    active_status: true,
    genre: "Adventure",
    image_link: "https://example.com/images/deep_sea_explorer.jpg",
    bundle_price: 24.99,
  },
  {
    game_name: "Alien Invasion",
    game_id: "G022",
    client_id: "C022",
    create_date: "2024-10-30",
    active_status: false,
    genre: "Shooter",
    image_link: "https://example.com/images/alien_invasion.jpg",
    bundle_price: 14.99,
  },
  {
    game_name: "Medieval Quest",
    game_id: "G023",
    client_id: "C023",
    create_date: "2024-11-05",
    active_status: true,
    genre: "Fantasy",
    image_link: "https://example.com/images/medieval_quest.jpg",
    bundle_price: 19.99,
  },
  {
    game_name: "Futuristic Racing",
    game_id: "G024",
    client_id: "C024",
    create_date: "2024-12-01",
    active_status: true,
    genre: "Racing",
    image_link: "https://example.com/images/futuristic_racing.jpg",
    bundle_price: 34.99,
  },
  {
    game_name: "Steampunk Saga",
    game_id: "G025",
    client_id: "C025",
    create_date: "2024-01-15",
    active_status: true,
    genre: "Adventure",
    image_link: "https://example.com/images/steampunk_saga.jpg",
    bundle_price: 24.99,
  },
  {
    game_name: "Magic Academy",
    game_id: "G026",
    client_id: "C026",
    create_date: "2024-02-20",
    active_status: false,
    genre: "Fantasy",
    image_link: "https://example.com/images/magic_academy.jpg",
    bundle_price: 29.99,
  },
  {
    game_name: "Ancient Legends",
    game_id: "G027",
    client_id: "C027",
    create_date: "2024-03-30",
    active_status: true,
    genre: "Adventure",
    image_link: "https://example.com/images/ancient_legends.jpg",
    bundle_price: 39.99,
  },
  {
    game_name: "Space Colony",
    game_id: "G028",
    client_id: "C028",
    create_date: "2024-04-10",
    active_status: true,
    genre: "Simulation",
    image_link: "https://example.com/images/space_colony.jpg",
    bundle_price: 24.99,
  },
  {
    game_name: "Viking Raid",
    game_id: "G029",
    client_id: "C029",
    create_date: "2024-05-05",
    active_status: true,
    genre: "Action",
    image_link: "https://example.com/images/viking_raid.jpg",
    bundle_price: 29.99,
  },
  {
    game_name: "Robot Revolution",
    game_id: "G030",
    client_id: "C030",
    create_date: "2024-06-15",
    active_status: false,
    genre: "Sci-Fi",
    image_link: "https://example.com/images/robot_revolution.jpg",
    bundle_price: 34.99,
  },
  {
    game_name: "Dragon Slayer",
    game_id: "G031",
    client_id: "C031",
    create_date: "2024-07-20",
    active_status: true,
    genre: "Fantasy",
    image_link: "https://example.com/images/dragon_slayer.jpg",
    bundle_price: 39.99,
  },
  {
    game_name: "Jungle Expedition",
    game_id: "G032",
    client_id: "C032",
    create_date: "2024-08-25",
    active_status: true,
    genre: "Adventure",
    image_link: "https://example.com/images/jungle_expedition.jpg",
    bundle_price: 24.99,
  },
  {
    game_name: "Cyber Warriors",
    game_id: "G033",
    client_id: "C033",
    create_date: "2024-09-10",
    active_status: true,
    genre: "Sci-Fi",
    image_link: "https://example.com/images/cyber_warriors.jpg",
    bundle_price: 34.99,
  },
  {
    game_name: "Urban Crime",
    game_id: "G034",
    client_id: "C034",
    create_date: "2024-10-05",
    active_status: false,
    genre: "Action",
    image_link: "https://example.com/images/urban_crime.jpg",
    bundle_price: 19.99,
  },
  {
    game_name: "Alien Quest",
    game_id: "G035",
    client_id: "C035",
    create_date: "2024-11-12",
    active_status: true,
    genre: "Adventure",
    image_link: "https://example.com/images/alien_quest.jpg",
    bundle_price: 29.99,
  },
  {
    game_name: "High Seas Battle",
    game_id: "G036",
    client_id: "C036",
    create_date: "2024-12-20",
    active_status: true,
    genre: "Strategy",
    image_link: "https://example.com/images/high_seas_battle.jpg",
    bundle_price: 39.99,
  },
  {
    game_name: "Gothic Horror",
    game_id: "G037",
    client_id: "C037",
    create_date: "2024-01-22",
    active_status: true,
    genre: "Horror",
    image_link: "https://example.com/images/gothic_horror.jpg",
    bundle_price: 24.99,
  },
  {
    game_name: "Mystic Realms",
    game_id: "G038",
    client_id: "C038",
    create_date: "2024-02-28",
    active_status: false,
    genre: "Fantasy",
    image_link: "https://example.com/images/mystic_realms.jpg",
    bundle_price: 34.99,
  },
  {
    game_name: "Space Pirates",
    game_id: "G039",
    client_id: "C039",
    create_date: "2024-03-15",
    active_status: true,
    genre: "Sci-Fi",
    image_link: "https://example.com/images/space_pirates.jpg",
    bundle_price: 29.99,
  },
  {
    game_name: "Robo Rescue",
    game_id: "G040",
    client_id: "C040",
    create_date: "2024-04-10",
    active_status: true,
    genre: "Action",
    image_link: "https://example.com/images/robo_rescue.jpg",
    bundle_price: 19.99,
  },
  {
    game_name: "Magic Duel",
    game_id: "G041",
    client_id: "C041",
    create_date: "2024-05-25",
    active_status: false,
    genre: "Fantasy",
    image_link: "https://example.com/images/magic_duel.jpg",
    bundle_price: 24.99,
  },
  {
    game_name: "Underground Racing",
    game_id: "G042",
    client_id: "C042",
    create_date: "2024-06-15",
    active_status: true,
    genre: "Racing",
    image_link: "https://example.com/images/underground_racing.jpg",
    bundle_price: 34.99,
  },
  {
    game_name: "Haunted Manor",
    game_id: "G043",
    client_id: "C043",
    create_date: "2024-07-20",
    active_status: true,
    genre: "Horror",
    image_link: "https://example.com/images/haunted_manor.jpg",
    bundle_price: 29.99,
  },
  {
    game_name: "Warrior's Quest",
    game_id: "G044",
    client_id: "C044",
    create_date: "2024-08-25",
    active_status: true,
    genre: "Fantasy",
    image_link: "https://example.com/images/warriors_quest.jpg",
    bundle_price: 39.99,
  },
  {
    game_name: "Epic Journey",
    game_id: "G045",
    client_id: "C045",
    create_date: "2024-09-10",
    active_status: true,
    genre: "Adventure",
    image_link: "https://example.com/images/epic_journey.jpg",
    bundle_price: 24.99,
  },
  {
    game_name: "Galactic Battle",
    game_id: "G046",
    client_id: "C046",
    create_date: "2024-10-05",
    active_status: false,
    genre: "Sci-Fi",
    image_link: "https://example.com/images/galactic_battle.jpg",
    bundle_price: 34.99,
  },
  {
    game_name: "Secret Agent",
    game_id: "G047",
    client_id: "C047",
    create_date: "2024-11-15",
    active_status: true,
    genre: "Stealth",
    image_link: "https://example.com/images/secret_agent.jpg",
    bundle_price: 29.99,
  },
  {
    game_name: "Treasure Hunt",
    game_id: "G048",
    client_id: "C048",
    create_date: "2024-12-10",
    active_status: true,
    genre: "Adventure",
    image_link: "https://example.com/images/treasure_hunt.jpg",
    bundle_price: 24.99,
  },
  {
    game_name: "Alien Encounter",
    game_id: "G049",
    client_id: "C049",
    create_date: "2024-01-05",
    active_status: true,
    genre: "Sci-Fi",
    image_link: "https://example.com/images/alien_encounter.jpg",
    bundle_price: 34.99,
  },
  {
    game_name: "Dino Adventure",
    game_id: "G050",
    client_id: "C050",
    create_date: "2024-02-15",
    active_status: false,
    genre: "Adventure",
    image_link: "https://example.com/images/dino_adventure.jpg",
    bundle_price: 19.99,
  },
  {
    game_name: "Deep Sea Explorer",
    game_id: "G051",
    client_id: "C051",
    create_date: "2024-09-25",
    active_status: true,
    genre: "Adventure",
    image_link: "https://example.com/images/deep_sea_explorer.jpg",
    bundle_price: 24.99,
  },
  {
    game_name: "Alien Invasion",
    game_id: "G052",
    client_id: "C052",
    create_date: "2024-10-30",
    active_status: false,
    genre: "Shooter",
    image_link: "https://example.com/images/alien_invasion.jpg",
    bundle_price: 14.99,
  },
];
