export const gameList = {
  categories: [
    {
      groupTitle: "Platform Games",
      groupId: "001",
      items: [
        { id: "001-01", title: "Sky Jumpers" },
        { id: "001-02", title: "Pixel Pioneers" },
        { id: "001-03", title: "Jump Quest" },
        { id: "001-04", title: "Block Hoppers" },
        { id: "001-05", title: "Castle Climbers" },
        { id: "001-06", title: "Platform Legends" },
        { id: "001-07", title: "Skyway Adventures" },
        { id: "001-08", title: "Retro Runners" },
        { id: "001-09", title: "Vertical Ventures" },
        { id: "001-10", title: "Gravity Defiers" },
      ],
    },
    {
      groupTitle: "Shooter Games",
      groupId: "002",
      items: [
        { id: "002-01", title: "Bullet Storm" },
        { id: "002-02", title: "Rage Runners" },
        { id: "002-03", title: "Gun Blaze" },
        { id: "002-04", title: "Stealth Shooter" },
        { id: "002-05", title: "Tactical Ops" },
        { id: "002-06", title: "Firepower Fury" },
        { id: "002-07", title: "Rapid Fire" },
        { id: "002-08", title: "Vortex Blasters" },
        { id: "002-09", title: "Gunfight Arena" },
        { id: "002-10", title: "Combat Surge" },
      ],
    },
    {
      groupTitle: "Fighting Games",
      groupId: "003",
      items: [
        { id: "003-01", title: "Battle Brawlers" },
        { id: "003-02", title: "Ultimate Duel" },
        { id: "003-03", title: "Rage Clash" },
        { id: "003-04", title: "Fist of Fury" },
        { id: "003-05", title: "Arena Combat" },
        { id: "003-06", title: "Warriors' Arena" },
        { id: "003-07", title: "Power Strike" },
        { id: "003-08", title: "Gladiator Legends" },
        { id: "003-09", title: "Combat Legends" },
        { id: "003-10", title: "Street Showdown" },
      ],
    },
    {
      groupTitle: "Beat 'em Up Games",
      groupId: "004",
      items: [
        { id: "004-01", title: "Street Brawlers" },
        { id: "004-02", title: "City Smash" },
        { id: "004-03", title: "Hero Rampage" },
        { id: "004-04", title: "Battle Streets" },
        { id: "004-05", title: "Rumble Squad" },
        { id: "004-06", title: "Urban Brawl" },
        { id: "004-07", title: "Fight Brigade" },
        { id: "004-08", title: "Smash City" },
        { id: "004-09", title: "Brawl Masters" },
        { id: "004-10", title: "Rage Street" },
      ],
    },
    {
      groupTitle: "Stealth Games",
      groupId: "005",
      items: [
        { id: "005-01", title: "Shadow Assassin" },
        { id: "005-02", title: "Silent Strike" },
        { id: "005-03", title: "Covert Ops" },
        { id: "005-04", title: "Sneak Tactics" },
        { id: "005-05", title: "Stealth Hunter" },
        { id: "005-06", title: "Infiltration X" },
        { id: "005-07", title: "Whispering Shadows" },
        { id: "005-08", title: "Shadow Wars" },
        { id: "005-09", title: "Camouflage Agents" },
        { id: "005-10", title: "Stealth Recon" },
      ],
    },
    {
      groupTitle: "Survival Games",
      groupId: "006",
      items: [
        { id: "006-01", title: "Last Stand" },
        { id: "006-02", title: "Wilderness Survivor" },
        { id: "006-03", title: "Endurance Quest" },
        { id: "006-04", title: "Survive & Thrive" },
        { id: "006-05", title: "Isolation Survival" },
        { id: "006-06", title: "Survivor's Edge" },
        { id: "006-07", title: "Lost World" },
        { id: "006-08", title: "Hardened Survival" },
        { id: "006-09", title: "Ultimate Survivalist" },
        { id: "006-10", title: "Survival Grounds" },
      ],
    },
    {
      groupTitle: "Rhythm Games",
      groupId: "007",
      items: [
        { id: "007-01", title: "Beat Frenzy" },
        { id: "007-02", title: "Rhythm Revolution" },
        { id: "007-03", title: "Dance Fever" },
        { id: "007-04", title: "Groove Master" },
        { id: "007-05", title: "Melody Clash" },
        { id: "007-06", title: "Tempo Quest" },
        { id: "007-07", title: "Beat Sync" },
        { id: "007-08", title: "Rhythm Clash" },
        { id: "007-09", title: "Dance Revolution" },
        { id: "007-10", title: "Pulse Control" },
      ],
    },
    {
      groupTitle: "Battle Royale Games",
      groupId: "008",
      items: [
        { id: "008-01", title: "Last Man Standing" },
        { id: "008-02", title: "Battle Royale Legends" },
        { id: "008-03", title: "Survival Royale" },
        { id: "008-04", title: "Warzone Battle" },
        { id: "008-05", title: "Final Fight Royale" },
        { id: "008-06", title: "Ultimate Showdown" },
        { id: "008-07", title: "Royale Rivals" },
        { id: "008-08", title: "Battle Blitz" },
        { id: "008-09", title: "Combat Royale" },
        { id: "008-10", title: "Survivor Royale" },
      ],
    },
  ],
};
